name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_FROM_API: 1
  HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}

concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enable debug mode
        if: runner.debug
        run: |
          echo "HOMEBREW_DEBUG=1" >> "${GITHUB_ENV}"
          echo "HOMEBREW_VERBOSE=1" >> "${GITHUB_ENV}"
      - name: Install Casks
        run: |
          brew install --cask ./Casks/*.rb
